- hosts: mongo
  sudo: true
  tasks:
    - name: downroad mongo repo
      shell: |
        echo "[MongoDB]
        name=MongoDB Repository
        baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64
        gpgcheck=0
        enabled=1" | sudo tee -a /etc/yum.repos.d/mongodb.repo
    - name: install mongo
      yum: pkg=mongodb-org
    - name: start mongo
      service: name=mongod state=started enabled=yes

